// This is a Java code generated by an AI assistant. 
import java.util.Random;
class RandomInteger {
    public static void main(String[] args) {
        Random rand = new Random();
        int randomInt = rand.nextInt((10 - 5) + 1) + 5;
        System.out.println("A random integer between 5 and 10 is: " + randomInt);
    }
}
